<?php

declare(strict_types=1);

return [
    'title' => 'EWall',
    'sitename' => 'foodfriendfinder',
    'subtitle' => 'Find restaurants, specials, and coupons for free',
    'sottotitolo_comune' => '',
    'generator' => '',
    'charset' => 'UTF-8',
    'author' => '',
    'description' => '',
    'keywords' => '',
    'nome_regione' => '',
    'nome_comune' => '',
    'site_title' => '',
    'logo' => 'camping::img/logo.png',
    'favicon' => 'egea::img/favicon.png',
    'logo_header' => 'ewall::img/logo.png',
    'logo_footer' => 'ewall::img/logo.png',
    'logo_img' => 'ewall::img/logo.png',
    'logo_square' => 'ewall::img/logo.png',
    'logo_footer_img' => 'ewall::img/logo.png',
    'logo_alt' => 'Logo',
    'hide_megamenu' => false,
    'hero_type' => 'with_megamenu_bottom',
    'facebook_href' => 'aa',
    'twitter_href' => '',
    'youtube_href' => '',
    'fastlink' => false,
    'color_primary' => '#0071b0',
    'color_title' => 'white',
    'color_megamenu' => '#d60021',
    'color_hamburger' => '#000',
    'color_banner' => '#000',
];
